name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * 7' # Every Sunday at 12:00
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch from Medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/@hendrikprinsza/feed"
