on:
  schedule:
    - cron: 0 10 * * 7 # Every Sunday at 10:00

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch from Medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest medium data"
          feed_list: "https://hendrikprinsza.medium.com/feed?max_post_count=10&retry_count=3"

  
