name: Do all workflows
on:
  schedule:
    - cron: '0 12 * * 7' # Every Sunday at 12:00
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch from Medium
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM"
          commit_message: "Updated readme with the latest medium data"
          feed_list: "https://hendrikprinsza.medium.com/feed?max_post_count=10&retry_count=3"

  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/7403334"
  
  fetch-latest-stats-job:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Fetch latest images
        run: npm run mystats-images
