name: "Stats Workflow"
on:
  schedule:
    - cron: "0 12 * * 7" # At 12:00 on Sunday.
  workflow_dispatch: # Allow manual trigger

permissions:

jobs:
  fetch-latest-stats-job:
    name: Update this repo README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run mystats-images
