name: Stats Workflow
on:
  schedule:
    # Runs every night
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fetch-latest-stats-job:
    name: Update this repo README with latest stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i --force
      - run: npm run mystats-images
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

