on:
  schedule:
    - cron: 0 12 * * 7 # Every Sunday at 12:00

jobs:
  fetch-latest-stats-job:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Fetch latest images
        run: npm run mystats-images
